//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace EMS_Oddhoyon_Business
{
    public partial class oemsbdv2_bmsc_dbEntities : ObjectContext
    {
        public const string ConnectionString = "name=oemsbdv2_bmsc_dbEntities";
        public const string ContainerName = "oemsbdv2_bmsc_dbEntities";
    
        #region Constructors
    
        public oemsbdv2_bmsc_dbEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public oemsbdv2_bmsc_dbEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public oemsbdv2_bmsc_dbEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Tbl_DateTime> Tbl_DateTime
        {
            get { return _tbl_DateTime  ?? (_tbl_DateTime = CreateObjectSet<Tbl_DateTime>("Tbl_DateTime")); }
        }
        private ObjectSet<Tbl_DateTime> _tbl_DateTime;
    
        public ObjectSet<Tbl_Events> Tbl_Events
        {
            get { return _tbl_Events  ?? (_tbl_Events = CreateObjectSet<Tbl_Events>("Tbl_Events")); }
        }
        private ObjectSet<Tbl_Events> _tbl_Events;
    
        public ObjectSet<Tbl_Gallery> Tbl_Gallery
        {
            get { return _tbl_Gallery  ?? (_tbl_Gallery = CreateObjectSet<Tbl_Gallery>("Tbl_Gallery")); }
        }
        private ObjectSet<Tbl_Gallery> _tbl_Gallery;
    
        public ObjectSet<Tbl_News> Tbl_News
        {
            get { return _tbl_News  ?? (_tbl_News = CreateObjectSet<Tbl_News>("Tbl_News")); }
        }
        private ObjectSet<Tbl_News> _tbl_News;
    
        public ObjectSet<Tbl_Notice> Tbl_Notice
        {
            get { return _tbl_Notice  ?? (_tbl_Notice = CreateObjectSet<Tbl_Notice>("Tbl_Notice")); }
        }
        private ObjectSet<Tbl_Notice> _tbl_Notice;
    
        public ObjectSet<Qry_EmployeeBasicInfo> Qry_EmployeeBasicInfo
        {
            get { return _qry_EmployeeBasicInfo  ?? (_qry_EmployeeBasicInfo = CreateObjectSet<Qry_EmployeeBasicInfo>("Qry_EmployeeBasicInfo")); }
        }
        private ObjectSet<Qry_EmployeeBasicInfo> _qry_EmployeeBasicInfo;

        #endregion
    }
}
