//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace EMS_Oddhoyon_Business
{
    [DataContract(IsReference = true)]
    public partial class Tbl_News: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int News_ID
        {
            get { return _news_ID; }
            set
            {
                if (_news_ID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'News_ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _news_ID = value;
                    OnPropertyChanged("News_ID");
                }
            }
        }
        private int _news_ID;
    
        [DataMember]
        public string News_Title
        {
            get { return _news_Title; }
            set
            {
                if (_news_Title != value)
                {
                    _news_Title = value;
                    OnPropertyChanged("News_Title");
                }
            }
        }
        private string _news_Title;
    
        [DataMember]
        public string News_Description
        {
            get { return _news_Description; }
            set
            {
                if (_news_Description != value)
                {
                    _news_Description = value;
                    OnPropertyChanged("News_Description");
                }
            }
        }
        private string _news_Description;
    
        [DataMember]
        public Nullable<System.DateTime> News_ExpireDate
        {
            get { return _news_ExpireDate; }
            set
            {
                if (_news_ExpireDate != value)
                {
                    _news_ExpireDate = value;
                    OnPropertyChanged("News_ExpireDate");
                }
            }
        }
        private Nullable<System.DateTime> _news_ExpireDate;
    
        [DataMember]
        public string News_Status
        {
            get { return _news_Status; }
            set
            {
                if (_news_Status != value)
                {
                    _news_Status = value;
                    OnPropertyChanged("News_Status");
                }
            }
        }
        private string _news_Status;
    
        [DataMember]
        public Nullable<int> News_AddBy
        {
            get { return _news_AddBy; }
            set
            {
                if (_news_AddBy != value)
                {
                    _news_AddBy = value;
                    OnPropertyChanged("News_AddBy");
                }
            }
        }
        private Nullable<int> _news_AddBy;
    
        [DataMember]
        public Nullable<System.DateTime> News_AddDate
        {
            get { return _news_AddDate; }
            set
            {
                if (_news_AddDate != value)
                {
                    _news_AddDate = value;
                    OnPropertyChanged("News_AddDate");
                }
            }
        }
        private Nullable<System.DateTime> _news_AddDate;
    
        [DataMember]
        public Nullable<int> News_UpdateBy
        {
            get { return _news_UpdateBy; }
            set
            {
                if (_news_UpdateBy != value)
                {
                    _news_UpdateBy = value;
                    OnPropertyChanged("News_UpdateBy");
                }
            }
        }
        private Nullable<int> _news_UpdateBy;
    
        [DataMember]
        public Nullable<System.DateTime> News_UpdateDate
        {
            get { return _news_UpdateDate; }
            set
            {
                if (_news_UpdateDate != value)
                {
                    _news_UpdateDate = value;
                    OnPropertyChanged("News_UpdateDate");
                }
            }
        }
        private Nullable<System.DateTime> _news_UpdateDate;
    
        [DataMember]
        public Nullable<System.DateTime> News_PublishDate
        {
            get { return _news_PublishDate; }
            set
            {
                if (_news_PublishDate != value)
                {
                    _news_PublishDate = value;
                    OnPropertyChanged("News_PublishDate");
                }
            }
        }
        private Nullable<System.DateTime> _news_PublishDate;
    
        [DataMember]
        public byte[] News_Picture
        {
            get { return _news_Picture; }
            set
            {
                if (_news_Picture != value)
                {
                    _news_Picture = value;
                    OnPropertyChanged("News_Picture");
                }
            }
        }
        private byte[] _news_Picture;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
