<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="HistoryWebForm.aspx.cs" Inherits="EMS_Oddhoyon_Web.AboutUs.HistoryWebForm" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
 <h1 class="section-heading text-highlight">
	<span class="line">History</span>
	</h1>
    <div class="section-content">  
   <div class="entry-content">
	<p style="text-align: justify;">Education makes man proceed to accomplishment flourishing his dormant mental strength. Again, it is proper education which forms the basement of economy of a country and becomes an inevitable essence for its gradual development. The ministry of education of the People’s Republic of Bangladesh Government has taken a project of 114 crore taka for establishing 11 Model Schools and Colleges in six divisional cities including Dhaka city for spreading &amp; modernizing education system, and to solve the prevailing admission problem in educational institutions. The project was approved on 31 January, 2006 at a meeting of ECNEC (Executive Committee of National Economic Council). The only purpose of the project is to decrease the discrimination in the local level of the country by creating developed management in higher secondary education. Barisal Model School &amp; College which was established in 2007 is one of the triumphant endeavours of this project. Prof. Md. Nurul Amin (BCS, General Education) joined at Barisal Model School &amp; College on 15 April, 2007 as a founder principal. After joining the principal, other teachers &amp; &nbsp;stuffs joined by turns. With the heartfelt effort of the principal, the other teachers and staffs, Barisal Model School &amp; College launched its 1st admission program in HSC from 2007-08. Later, from the year of 2008 the secondary level school education from six to ten was started in this institution. In fact, Barisal Model School &amp; College set out its expedition from the year of 2008. Barisal Model School &amp; College is situated in an aristocratic area at the heart of Barisal city at the north side of Bangabandhu Uddayn in a serene and eye-catching location of 1.80 acre land with a five storied building. There are two separate gates in the north and south sides of the college and one of them is allowed only for the girls. There is a beautiful garden in the college compound. There are three stairs for lifting from the ground floor to the fourth floor. Among the three stairs, one is allowed only for the girls. There are 75 rooms, 10 science laboratories with all modern amenities, a computer lab with 50 computers, a library with about six thousand books and a gymnasium for physical fitness in the multi-storied building.</p>
	</div><!-- .entry-content -->
   </div><!--//page-row-->	
</asp:Content>
